apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: todo-deployment
  namespace: tudo-ns 
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: tudo-app 
  template: 
    containers:
      metadata: 
        labels: 
          app: tudo-app
      spec:
        containers: 
          - name: tudo-container
            image: rk0617/tudoapp:latest
            containerPort: 3000
      