apiVersion: v1 
kind: Pod 
metadata: 
  name: tudo-Pod
  namespace: tudo-ns
spec:
  containers:
    - name: tudo-container
      image: rk0617/tudoapp:latest 
      ports: 
        - containerPort:3000