kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: tudo-deployment-hpa 
  namespace: tudo-ns 
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: tudo-app 
  template:
      metadata: 
        labels: 
          app: tudo-app
      spec:
        containers: 
          - name: tudo-container
            image: rk0617/tudoapp:latest
            ports:
              - containerPort: 3000
            resource: 
              requests: 
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m 
                memory: 256Mi